#' @title Calculate Kidney-to-Body-Weight ratio Z-Scores for each animal in a given STUDYID from SQLite Database or `.xpt` Files
#'
#' @description
#' Pre-requisites steps
#' library(magrittr)   #to load %>% used in the get_compile_data
#' 1) Install and load the devtools::load_all() to make sure R can read the SENDQSAR package.
#'     a. get_compile_data - not mandatory to run this function as default is NULL
#'     b. get_bw_score - not mandatory as set to default
#' 2) Make the path to the data set is accurately set.
#' 3) Two arguments to the functions are mandatory: Studyid & path_db. Rest all default
#'
#' @param studyid Character. STUDYID number. (Mandatory) Defaults to `NULL`.
#'    Required for SQLite databases (`use_xpt_file = FALSE`).
#'    Must be `NULL` for `.xpt` files (`use_xpt_file = TRUE`).
#' @param path_db Character. Path to the SQLite database file containing .db file OR path to a folder containing `.xpt` files. (Mandatory).
#' @param fake_study Logical. Optional, Whether the study data is generated by the `SENDsanitizer` package. Defaults to `FALSE`.
#' @param use_xpt_file Logical. Optional. Whether to retrieve study data from `.xpt` files instead of the SQLite database. Defaults to `FALSE`.
#' @param master_compiledata Optional, character \cr
#'   If `master_compiledata` is not supplied (i.e., `NULL`), the function will automatically call the `get_compile_data` function to calculate it.
#' @param bwzscore_BW Optional, data.frame. \cr
#'   if `bwzscore_BW` is not supplied (i.e., `NULL`), the function will automatically call the `get_bw_score` function to calculate it.
#' @param return_individual_scores Optional, logical \cr
#'   If TRUE, the function returns individual scores for each domain by averaging the scores of all subjects/animals (`USUBJID`) in the study. Default is `FALSE`.
#'   in another words, if TRUE, it is calculating the average kidney-to-body weight z-score across all animals in the HD group, grouped by STUDYID
#' @param return_zscore_by_USUBJID Optional, logical \cr
#'    If `TRUE`, the function returns Z-scores for each animal/subject by `USUBJID`. Default is `FALSE`.
#'
#' @return
#' A data frame containing Kidney-to-body-weight ratio z-scores:
#' - If `return_individual_scores = TRUE`: Returns averaged Z-scores for each  domain per `studyid`.
#' - If `return_zscore_by_USUBJID = TRUE`: Returns Z-score for each animal/subject by `USUBJID` for each domain per `studyid`.
#' - Otherwise, a summarized BW score for the specified `studyid`.
#'
#' @examples
#' \dontrun{
#' three ways to call studyid; 1&2)enter it is done in below result1 and result2, 3) studyid <- "123456" #load it before calling function.
#' # Example 1: Default averaged scores
#' result1 <- kidneytobw_score(
#'                           studyid = "1234123",
#'                           path_db = "C:/path/to/database.db")
#' head(result1)
#'
#' # Example 2: Individual scores by study
#' result2 <- kidneytobw_score("123456", path_db,
#'                           master_compiledata = NULL,
#'                           bwzscore_BW = NULL,
#'                           return_individual_scores = TRUE,
#'                           return_zscore_by_USUBJID = FALSE)
#' head(result2)
#'
#' # Example 3: Z-scores by USUBJID
#' result3 <- kidneytobw_score(studyid, path_db,
#'                           master_compiledata = NULL,
#'                           bwzscore_BW = NULL,
#'                           return_individual_scores = FALSE,
#'                           return_zscore_by_USUBJID = TRUE)
#' head(result3)
#' }
#' @importFrom RSQLite dbConnect
#' @importFrom RSQLite SQLite
#' @importFrom magrittr %>%

kidneytobw_score <- function(studyid = NULL, path_db, fake_study = FALSE, use_xpt_file = FALSE,
                                     master_compiledata = NULL, bwzscore_BW = NULL,
                                     return_individual_scores = FALSE, return_zscore_by_USUBJID = FALSE) {

  # Embedded helper: Fetch domain data
  fetch_domain_data <- function(db_connection, domain_name, studyid) {
    domain_name <- toupper(domain_name)
    query <- paste0('SELECT * FROM ', domain_name, " WHERE STUDYID = :x")
    DBI::dbGetQuery(db_connection, statement = query, params = list(x = studyid))
  }

  # Embedded helper: Safe SD calculation
  safe_sd <- function(x) {
    sd_val <- sd(x, na.rm = TRUE)
    ifelse(sd_val == 0, NA, sd_val)
  }

  # Embedded helper: Calculate kidney z-scores
  calculate_kidney_zscores <- function(df, bw_data, compile_data) {
    kidney_data <- df %>%
      dplyr::filter(stringr::str_detect(OMSPEC, "KIDNEY"), OMTEST == "Weight") %>%
      dplyr::select(USUBJID, OMSTRESN)

    kidney_data_filtered <- kidney_data %>%
      dplyr::filter(USUBJID %in% compile_data$USUBJID) %>%
      dplyr::left_join(compile_data %>% dplyr::select(STUDYID, USUBJID, ARMCD), by = "USUBJID") %>%
      dplyr::left_join(bw_data %>% dplyr::select(USUBJID, finalbodyweight), by = "USUBJID") %>%
      dplyr::mutate(kidneyToBW = OMSTRESN / finalbodyweight)

    kidney_data_zscore <- kidney_data_filtered %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        kidneyToBW = replace(kidneyToBW, is.infinite(kidneyToBW), NA),
        mean_vehicle = mean(kidneyToBW[ARMCD == "vehicle"], na.rm = TRUE),
        sd_vehicle = safe_sd(kidneyToBW[ARMCD == "vehicle"])
      ) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(kidneyToBW_zscore = abs((kidneyToBW - mean_vehicle) / sd_vehicle)) %>%
      dplyr::select(STUDYID, USUBJID, ARMCD, kidneyToBW_zscore)

    return(kidney_data_zscore)
  }

  if (return_individual_scores && return_zscore_by_USUBJID) {
    stop("Both 'return_individual_scores' and 'return_zscore_by_USUBJID' cannot be TRUE.")
  }

  # Load Organ Measurements
  if (use_xpt_file) {
    om <- haven::read_xpt(fs::path(path_db, 'om.xpt'))
    studyid <- NULL
  } else {
    db_connection <- DBI::dbConnect(RSQLite::SQLite(), dbname = path_db)
    om <- fetch_domain_data(db_connection, 'om', studyid)
    DBI::dbDisconnect(db_connection)
  }

  # Get compile data if needed
  if (is.null(master_compiledata)) {
    master_compiledata <- get_compile_data(studyid = studyid, path_db = path_db, fake_study = fake_study, use_xpt_file = use_xpt_file)
  }

  # Get bodyweight scores if needed
  if (is.null(bwzscore_BW)) {
    bwzscore_BW <- get_bw_score(studyid = studyid, path_db = path_db, fake_study = fake_study,
                                use_xpt_file = use_xpt_file, master_compiledata = master_compiledata,
                                return_individual_scores = TRUE, return_zscore_by_USUBJID = FALSE)
  }

  # Calculate kidney z-scores
  kidney_zscores <- calculate_kidney_zscores(om, bwzscore_BW, master_compiledata)

  # Filter High Dose (HD) only
  hd_kidney_zscores <- kidney_zscores %>%
    dplyr::filter(ARMCD == "HD")

  # Build the output based on flags
  result <- NULL
  if (return_individual_scores) {
    result <- hd_kidney_zscores %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::summarize(avg_kidneyToBW_zscore = mean(kidneyToBW_zscore, na.rm = TRUE)) %>%
      dplyr::mutate(avg_kidneyToBW_zscore = dplyr::case_when(
        avg_kidneyToBW_zscore >= 3 ~ 3,
        avg_kidneyToBW_zscore >= 2 ~ 2,
        avg_kidneyToBW_zscore >= 1 ~ 1,
        TRUE ~ 0
      ))
  } else if (return_zscore_by_USUBJID) {
    result <- hd_kidney_zscores %>%
      dplyr::mutate(kidneyToBW_zscore = dplyr::case_when(
        kidneyToBW_zscore >= 3 ~ 3,
        kidneyToBW_zscore >= 2 ~ 2,
        kidneyToBW_zscore >= 1 ~ 1,
        TRUE ~ 0
      )) %>%
      dplyr::select(STUDYID, USUBJID, kidneyToBW_zscore)
  } else {
    result <- hd_kidney_zscores %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::summarize(avg_kidneyToBW_zscore = mean(kidneyToBW_zscore, na.rm = TRUE)) %>%
      dplyr::mutate(avg_kidneyToBW_zscore = dplyr::case_when(
        avg_kidneyToBW_zscore >= 3 ~ 3,
        avg_kidneyToBW_zscore >= 2 ~ 2,
        avg_kidneyToBW_zscore >= 1 ~ 1,
        TRUE ~ 0
      ))
  }

  return(result)
}
